CREATE DATABASE db_juegos;
CREATE TABLE juego (
    ID BIGINT GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR(50) NOT NULL,
    CONSTRAINT pk_juego PRIMARY KEY (ID),
    CONSTRAINT uq_juego_nombre UNIQUE (NOMBRE)
);
