spring:
  application:
    name: ms-friendship
  config:
    import: classpath:actuator-defaults.yaml

  datasource:
    url: jdbc:postgresql://localhost:5440/db_friendship
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: false
    baseline-on-migrate: true

server:
  port: 8089
  forward-headers-strategy: framework

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
