spring:
  application:
    name: ms-friendship

  datasource:
    url: jdbc:postgresql://localhost:5440/db_friendship
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: false
    baseline-on-migrate: true

server:
  port: 8089