spring:
  application:
    name: ms-stats
  config:
    import: classpath:actuator-defaults.yaml

server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
