server:
  port: 9090
  servlet:
    context-path: /admin
spring:
  boot:
    admin:
      ui:
        public-url: http://localhost:8090
  application:
    name: ms-admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/